export const SampleCustomerData = {
    getCustomersData() {
        return [
            {
                id: '1',
                title: 'Mr.',
                firstName: 'John',
                lastName: 'Doe',
                email: 'johndoe@example.com',
                mobileNo: '0102025555',
            },
            {
                id: '2',
                title: 'Mrs.',
                firstName: 'Jane',
                lastName: 'Smith',
                email: 'janesmith@example.com',
                mobileNo: '0102035555',
            },
            {
                id: '3',
                title: 'Miss.',
                firstName: 'Alice',
                lastName: 'Johnson',
                email: 'alicejohnson@example.com',
                mobileNo: '0102045555',
            },
            {
                id: '4',
                title: 'Ms.',
                firstName: 'Emily',
                lastName: 'Davis',
                email: 'emilydavis@example.com',
                mobileNo: '0102055555',
            },
            {
                id: '5',
                title: 'Mr.',
                firstName: 'Michael',
                lastName: 'Brown',
                email: 'michaelbrown@example.com',
                mobileNo: '0102065555',
            },
            {
                id: '6',
                title: 'Mrs.',
                firstName: 'Laura',
                lastName: 'Wilson',
                email: 'laurawilson@example.com',
                mobileNo: '0102075555',
            },
            {
                id: '7',
                title: 'Miss.',
                firstName: 'Sarah',
                lastName: 'Taylor',
                email: 'sarahtaylor@example.com',
                mobileNo: '0102085555',
            },
            {
                id: '8',
                title: 'Ms.',
                firstName: 'Jessica',
                lastName: 'Anderson',
                email: 'jessicaanderson@example.com',
                mobileNo: '0102095555',
            },
            {
                id: '9',
                title: 'Mr.',
                firstName: 'David',
                lastName: 'Thomas',
                email: 'davidthomas@example.com',
                mobileNo: '0102105555',
            },
            {
                id: '10',
                title: 'Mrs.',
                firstName: 'Rachel',
                lastName: 'Martinez',
                email: 'rachelmartinez@example.com',
                mobileNo: '0102115555',
            },
            {
                id: '11',
                title: 'Miss.',
                firstName: 'Olivia',
                lastName: 'Hernandez',
                email: 'oliviahernandez@example.com',
                mobileNo: '0102125555',
            },
            {
                id: '12',
                title: 'Ms.',
                firstName: 'Sophia',
                lastName: 'Moore',
                email: 'sophiamoore@example.com',
                mobileNo: '0102135555',
            },
            {
                id: '13',
                title: 'Mr.',
                firstName: 'James',
                lastName: 'Jackson',
                email: 'jamesjackson@example.com',
                mobileNo: '0102145555',
            },
            {
                id: '14',
                title: 'Mrs.',
                firstName: 'Megan',
                lastName: 'White',
                email: 'meganwhite@example.com',
                mobileNo: '0102155555',
            },
            {
                id: '15',
                title: 'Miss.',
                firstName: 'Chloe',
                lastName: 'Harris',
                email: 'chloeharris@example.com',
                mobileNo: '0102165555',
            },
            {
                id: '16',
                title: 'Ms.',
                firstName: 'Amanda',
                lastName: 'Martin',
                email: 'amandamartin@example.com',
                mobileNo: '0102175555',
            },
            {
                id: '17',
                title: 'Mr.',
                firstName: 'Robert',
                lastName: 'Thompson',
                email: 'robertthompson@example.com',
                mobileNo: '0102185555',
            },
            {
                id: '18',
                title: 'Mrs.',
                firstName: 'Elizabeth',
                lastName: 'Garcia',
                email: 'elizabethgarcia@example.com',
                mobileNo: '0102195555',
            },
            {
                id: '19',
                title: 'Miss.',
                firstName: 'Anna',
                lastName: 'Martinez',
                email: 'annamartinez@example.com',
                mobileNo: '0102205555',
            },
            {
                id: '20',
                title: 'Ms.',
                firstName: 'Grace',
                lastName: 'Lee',
                email: 'gracelee@example.com',
                mobileNo: '0102215555',
            }
        ];
    }
}